name: ACR Build and Push
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: main
      SERVICE_NAME: a-container-acr

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: azure/docker-login@v1
        with:
          login-server: projectxpoc.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build docker image
      - name: Image Build
        run: |-
          docker build -t projectxpoc.azurecr.io/a-container-acr/$SERVICE_NAME:latest .

      # Push image to Azure Container Registry
      - name: Image Push
        run: |-
          docker push projectxpoc.azurecr.io/a-container-acr/$SERVICE_NAME:latest
